Extra:
    NoSkinName: "None"
    NoGenre: "Undefined"
    Male-Genre: "Male"
    Female-Genre: "Female"

Menu:
    MainGUI:
        Name: "&8My Skins"
        LastSkinLore:
        - "&fGenre: &7@skin-genre"
        - ""
        - " &e➥ Click to use"
        No-skin-selected:
            ID: red dye
            Color: white
            Name: "&cNo skin selected"
            Lore:
            - "&7It looks like you haven't selected"
            - "&7any skins, equip a skin using"
            - "&7the command &f/skins set <Nick>"
        Reload-skin:
            ID: barrier
            Color: white
            Name: "&aUpdate skin"
            Lore:
            - "&7Update the skin you are using"
            - ""
            - " &e➥ Click to update"
        Player-profile:
            ID: player head;@player
            Color: white
            Name: "&aSkin selected"
            Lore:
            - "&fSelected: &7@skin-selected"
            - "&fGenre: &7@skin-genre"
            - ""
            - "&8Your default skin will be your account" 
            - "&8if you are an original player, if"
            - "&8otherwise, your default skin will be the"
            - "&8server default skin"
            - ""
            - " &e➥ Click to reset your skin"

Messages:
    ChangeSkin:
    - "&aYou changed your skin to &f'@skinname'"
    EquippedSkin:
    - "&cYou are already using this skin!"